import { lazy, type ComponentType } from 'react'
import type { GameEntry } from './types'

const lazyGame = (loader: () => Promise<{ default: ComponentType }>) =>
  lazy(loader)

export const gameList: GameEntry[] = [
  {
    slug: 'bubble-wrap',
    title: '捏泡泡纸',
    description: '点击气泡，噗噗解压',
    icon: '🫧',
    Component: lazyGame(() => import('./bubble-wrap/Game')),
  },
  {
    slug: 'wooden-fish',
    title: '电子木鱼',
    description: '敲一敲，功德+1',
    icon: '🪵',
    Component: lazyGame(() => import('./wooden-fish/Game')),
  },
  {
    slug: 'spinner',
    title: '指尖陀螺',
    description: '拨动旋转，看惯性慢慢停',
    icon: '🌀',
    Component: lazyGame(() => import('./spinner/Game')),
  },
  {
    slug: 'color-sort',
    title: '试管倒水',
    description: '同色归位，过关解压',
    icon: '🧪',
    Component: lazyGame(() => import('./color-sort/Game')),
  },
  {
    slug: 'organize',
    title: '收纳抽屉',
    description: '把物品拖回正确格子',
    icon: '🗄️',
    Component: lazyGame(() => import('./organize/Game')),
  },
  {
    slug: 'whack',
    title: '打地鼠',
    description: '30 秒能敲多少只',
    icon: '🐹',
    Component: lazyGame(() => import('./whack/Game')),
  },
  {
    slug: 'shredder',
    title: '碎纸机',
    description: '拖纸条进机器粉碎',
    icon: '📄',
    Component: lazyGame(() => import('./shredder/Game')),
  },
  {
    slug: 'clean-screen',
    title: '擦玻璃',
    description: '擦掉雾气，露出蓝天',
    icon: '🪟',
    Component: lazyGame(() => import('./clean-screen/Game')),
  },
  {
    slug: 'breathing',
    title: '呼吸泡泡',
    description: '跟随节奏深呼吸',
    icon: '🫁',
    Component: lazyGame(() => import('./breathing/Game')),
  },
  {
    slug: 'doodle',
    title: '涂鸦板',
    description: '随意涂画，一键清空',
    icon: '🎨',
    Component: lazyGame(() => import('./doodle/Game')),
  },
  {
    slug: 'pop-bubbles',
    title: '戳泡泡',
    description: '点击上升的气泡',
    icon: '💭',
    Component: lazyGame(() => import('./pop-bubbles/Game')),
  },
  {
    slug: 'stress-ball',
    title: '捏压力球',
    description: '按住捏扁，松开回弹',
    icon: '🔴',
    Component: lazyGame(() => import('./stress-ball/Game')),
  },
  {
    slug: 'coin-flip',
    title: '抛硬币',
    description: '正面还是反面',
    icon: '🪙',
    Component: lazyGame(() => import('./coin-flip/Game')),
  },
  {
    slug: 'dice',
    title: '掷骰子',
    description: '摇一摇看点数',
    icon: '🎲',
    Component: lazyGame(() => import('./dice/Game')),
  },
  {
    slug: 'rps',
    title: '猜拳',
    description: '石头剪刀布对战',
    icon: '✊',
    Component: lazyGame(() => import('./rps/Game')),
  },
  {
    slug: 'rip-paper',
    title: '撕纸',
    description: '一条一条撕下去',
    icon: '📃',
    Component: lazyGame(() => import('./rip-paper/Game')),
  },
  {
    slug: 'zen-sand',
    title: '禅意沙盘',
    description: '拖动耙子画沙纹',
    icon: '🏜️',
    Component: lazyGame(() => import('./zen-sand/Game')),
  },
  {
    slug: 'rain-window',
    title: '雨窗',
    description: '点击溅开雨滴',
    icon: '🌧️',
    Component: lazyGame(() => import('./rain-window/Game')),
  },
  {
    slug: 'piano',
    title: '迷你钢琴',
    description: '点击琴键演奏',
    icon: '🎹',
    Component: lazyGame(() => import('./piano/Game')),
  },
  {
    slug: 'memory',
    title: '翻牌记忆',
    description: '配对相同图案',
    icon: '🃏',
    Component: lazyGame(() => import('./memory/Game')),
  },
  {
    slug: 'puzzle',
    title: '数字华容道',
    description: '滑动拼图还原',
    icon: '🔢',
    Component: lazyGame(() => import('./puzzle/Game')),
  },
  {
    slug: 'ripples',
    title: '水波纹',
    description: '点击水面起涟漪',
    icon: '🌊',
    Component: lazyGame(() => import('./ripples/Game')),
  },
  {
    slug: 'catch',
    title: '接星星',
    description: '移动篮子接住星星',
    icon: '🧺',
    Component: lazyGame(() => import('./catch/Game')),
  },
  {
    slug: 'stack',
    title: '叠方块',
    description: '对齐叠高塔',
    icon: '🧱',
    Component: lazyGame(() => import('./stack/Game')),
  },
  {
    slug: 'vacuum',
    title: '吸尘器',
    description: '吸走满地灰尘',
    icon: '🧹',
    Component: lazyGame(() => import('./vacuum/Game')),
  },
  {
    slug: 'water-plant',
    title: '浇水植物',
    description: '浇水看它长大',
    icon: '🌱',
    Component: lazyGame(() => import('./water-plant/Game')),
  },
  {
    slug: 'snow-globe',
    title: '雪球',
    description: '摇一摇雪花飞舞',
    icon: '❄️',
    Component: lazyGame(() => import('./snow-globe/Game')),
  },
  {
    slug: 'magnet',
    title: '磁铁',
    description: '拖动吸引铁屑',
    icon: '🧲',
    Component: lazyGame(() => import('./magnet/Game')),
  },
  {
    slug: 'peel-sticker',
    title: '揭贴纸',
    description: '撕开贴纸看惊喜',
    icon: '🏷️',
    Component: lazyGame(() => import('./peel-sticker/Game')),
  },
  {
    slug: 'stamp',
    title: '盖章',
    description: '在纸上盖满印章',
    icon: '📮',
    Component: lazyGame(() => import('./stamp/Game')),
  },
  {
    slug: 'pendulum',
    title: '钟摆',
    description: '拖动观察摆动',
    icon: '🔮',
    Component: lazyGame(() => import('./pendulum/Game')),
  },
  {
    slug: 'keyboard',
    title: '爆戳键盘',
    description: '狂按键盘解压',
    icon: '⌨️',
    Component: lazyGame(() => import('./keyboard/Game')),
  },
]

export function getGameBySlug(slug: string): GameEntry | undefined {
  return gameList.find((g) => g.slug === slug)
}
